<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AspireApp.ServiceDefaults\AspireApp.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\OpenApi\BuildingBlocks.OpenApi.csproj" />
    <ProjectReference Include="..\Payment.Application\Payment.Application.csproj" />
    <ProjectReference Include="..\Payment.Infrastructure\Payment.Infrastructure.csproj" />
  </ItemGroup>

</Project>
